---
iscsi_target_address: 10.0.0.1
iscsi_target_name: iqn.1999-07.com.example:diskarray.sn.88
iscsi_target_password: password

http_password: password
mysql_user: homeassistant
mysql_pass: password
mysql_root_pass: password

influx_admin_pass: password
influx_password: password

dyson_user: user@domain.com
dyson_pass: password

openweathermap_api_key: api_key

nvr_api_key: api_key
nvr_password: password

ha_git_repo: git@repo.com/ha-config

ssh_deployment_key: |
  -----BEGIN RSA PRIVATE KEY-----
  SSH DEPLOYMENT KEY
  -----END RSA PRIVATE KEY-----


