---
- name: "Install HA on Raspi"

  hosts: home_assistant
  roles:
    - role: iscsi
      tags: iscsi
    - role: docker
      tags: docker
    - role: docker-compose
      tags: docker
    - role: home-assistant
      tags: ha
  become: yes
